# Generated by Django 4.2 on 2024-01-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund_login', '0008_remove_customuser_forget_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='po_value',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='supplier_quote',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
