# Generated by Django 4.2 on 2024-01-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund_login', '0009_customuser_po_value_customuser_supplier_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='monthly_revenue',
            field=models.PositiveIntegerField(choices=[(0, '0 - 50k'), (1, '50k - 100k'), (2, '100k - 150k'), (3, '150k +')], default=0),
        ),
    ]
