# Generated by Django 4.2 on 2024-01-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund_login', '0010_alter_customuser_monthly_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='years_in_business',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
