# Generated by Django 4.2 on 2024-01-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund_login', '0013_alter_customuser_years_in_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='years_in_business',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
