# Generated by Django 4.2 on 2024-01-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund_login', '0015_customuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Incomplete', 'Incomplete'), ('Complete', 'Complete')], default='In Progress', max_length=20),
        ),
    ]
